//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISeeNEntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentIt02Entities : DbContext
    {
        public RentIt02Entities()
            : base("name=RentIt02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Media> MediaSet { get; set; }
        public virtual DbSet<Rental> RentalSet { get; set; }
        public virtual DbSet<Statistic> StatisticSet { get; set; }
        public virtual DbSet<Reminder> ReminderSet { get; set; }
    }
}
