//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISeeNEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
